Portfolio: Setup Portfolio
samiullahbahadur/Portfolio pull request #1
Opened 2022-01-12 10:35 UTC by samiullahbahadur

merge to main

2022-01-12 10:57 UTC, Amrhub requested changes
Hi @samiullahbahadur,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## To Highlight ✔️ 
✔️ All linters are passing
✔️ Documentated your project in a professional way
✔️ Clean code and easy to read

## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 10:57 UTC, Amrhub commented on index.html
> +        </div>
- [ ] Let's make sure we use `nav` tag instead of div for better HTML Semantic

2022-01-12 10:57 UTC, Amrhub commented on index.html
> +        </div>
- [ ] Let's make sure we use any image for styling purposes as a background image  in CSS we should only use images where we need it as part of content, Also, let's make sure we use the same background image as used in Figma 
![image](https://user-images.githubusercontent.com/87689547/149127362-3d424680-3163-4ab8-9221-c47c744b8ca9.png)

2022-01-13 13:06 UTC, andersonlebon approved these changes
## Hi @samiullahbahadur 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions

- [ ] Kindly I would recommend you add a good pull request description
![image](https://user-images.githubusercontent.com/65068771/149335510-aa529b23-dd0d-4bf2-8b2a-f87c42f8ab71.png)


- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-13 13:06 UTC, andersonlebon commented on index.html
> +                </ul> -->
## [OPTIONAL]
- [ ] To make this file more clear and clean I would suggest you remove all commented code.

2022-01-13 13:06 UTC, andersonlebon commented on README.md
> +
## [OPTIONAL]
- [ ] To make your `README` file look more professional. I would kindly suggest you add a screenshot of the first section of this project just only to give visitors a short review of how your project looks like. :clap:

2022-01-13 13:18 UTC, merged